---
# tasks file for eucalyptus-start

- name: Start NC
  service: name=eucalyptus-nc state=started
  when:
  - inventory_hostname in groups.nc
  tags:
  - services_start

- name: Start eucanetd
  service: name=eucanetd state=started
  when:
  - inventory_hostname in groups.nc
  - networking_mode == "EDGE"
  tags:
  - services_start
